using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace JobTracker.Models
{
    public class JobApplication
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; } // Primary key, auto generated by the database layer
        public string UserId { get; set; } // The unique ID of each User.
        [Required]
        public string Company { get; set; } // Name of the company or organization
        [Required]
        public string JobTitle { get; set; } // Title of the job or position
        [Required]
        public string Status { get; set; } // Applied, Interview, Rejected, etc.
        public DateOnly? ApplicationDate { get; set; } // Date the user applied for the position
        public string? Salary { get; set; } // Salary of the position
        public string? Notes { get; set; }
        public static List<SelectListItem>? Statuses { get; } =
        [
            new SelectListItem("Not Applied", "Not Applied"),
            new SelectListItem("Applied", "Applied"),
            new SelectListItem("Interview", "Interview"),
            new SelectListItem("Rejected", "Rejected"),
            new SelectListItem("Accepted", "Accepted")
        ];
    }
}